[package]
name = "FinSc-Multiset-Binary"
version = "0.3.0"
ipkg = "FinSc-Multiset-Binary.ipkg"

[custom.all.FinSc-Multiset-Core]
type = "local"
path = "../FinSc-Multiset-Core"
ipkg = "FinSc-Multiset-Core.ipkg"

[custom.all.FinSc-Multiset-Transform]
type = "local"
path = "../FinSc-Multiset-Transform"
ipkg = "FinSc-Multiset-Transform.ipkg"
