[custom.all.idris2-Boole]
type = "local"
path = "."
ipkg = "idris2-Boole.ipkg"

[custom.all.idris2-Multiset]
type = "local"
path = "../idris2-Multiset"
ipkg = "idris2-Multiset.ipkg"

[custom.all.idris2-Boole-test]
type = "local"
path = "."
ipkg = "idris2-Boole-test.ipkg"

[custom.all.idris2-QuickCheck]
type = "local"
path = "../idris2-QuickCheck"
ipkg = "idris2-QuickCheck.ipkg"
